import type { Client, Quote, Task, Training } from "./types";

export const seedTasks: Task[] = [
  {
    id: "t1",
    title: "Enviar orçamento de mangueiras ZEC para frigorífico (Agro)",
    segment: "Agro",
    priority: "Alta",
    status: "A Fazer",
    dueDate: "2026-07-25",
    notes: "Cliente pediu prazo de entrega e certificado de teste.",
  },
  {
    id: "t2",
    title: "Follow-up bomba Marzocchi — usina de mineração",
    segment: "Mineração",
    priority: "Alta",
    status: "Em Andamento",
    dueDate: "2026-07-24",
    notes: "Aguardando aprovação de compras do cliente.",
  },
  {
    id: "t3",
    title: "Agendar visita técnica Uniflex na planta industrial",
    segment: "Indústria",
    priority: "Média",
    status: "A Fazer",
    dueDate: "2026-07-29",
    notes: "",
  },
  {
    id: "t4",
    title: "Fechar treinamento Held com equipe de manutenção",
    segment: "Petróleo & Gás",
    priority: "Média",
    status: "Concluído",
    dueDate: "2026-07-18",
    notes: "Certificados emitidos e enviados por e-mail.",
  },
  {
    id: "t5",
    title: "Atualizar catálogo de crimpadoras Next Powertech",
    segment: "Indústria",
    priority: "Baixa",
    status: "A Fazer",
    dueDate: "2026-08-05",
    notes: "",
  },
];

export const seedQuotes: Quote[] = [
  {
    id: "q1",
    client: "Carlos Menezes",
    company: "AgroVale Alimentos",
    brand: "ZEC",
    segment: "Agro",
    value: 18500,
    status: "Enviado",
    date: "2026-07-20",
  },
  {
    id: "q2",
    client: "Fernanda Ribeiro",
    company: "Mineração Serra Azul",
    brand: "Marzocchi",
    segment: "Mineração",
    value: 42000,
    status: "Em Aberto",
    date: "2026-07-22",
  },
  {
    id: "q3",
    client: "Diego Santos",
    company: "Transfluid do Brasil — Manutenção",
    brand: "Transfluid",
    segment: "Petróleo & Gás",
    value: 27500,
    status: "Aprovado",
    date: "2026-07-10",
  },
  {
    id: "q4",
    client: "Marina Costa",
    company: "Metalúrgica Uniflex Sul",
    brand: "Uniflex",
    segment: "Indústria",
    value: 9800,
    status: "Perdido",
    date: "2026-07-05",
  },
];

export const seedClients: Client[] = [
  {
    id: "c1",
    name: "Carlos Menezes",
    company: "AgroVale Alimentos",
    segment: "Agro",
    phone: "(11) 98888-1234",
    lastContact: "2026-07-20",
  },
  {
    id: "c2",
    name: "Fernanda Ribeiro",
    company: "Mineração Serra Azul",
    segment: "Mineração",
    phone: "(31) 97777-5678",
    lastContact: "2026-07-22",
  },
  {
    id: "c3",
    name: "Diego Santos",
    company: "Refinaria Sul Petróleo",
    segment: "Petróleo & Gás",
    phone: "(21) 96666-4321",
    lastContact: "2026-07-10",
  },
];

export const seedTrainings: Training[] = [
  {
    id: "tr1",
    title: "Treinamento de crimpagem e testes de mangueiras",
    brand: "ZEC",
    client: "AgroVale Alimentos",
    date: "2026-08-01",
    location: "São Paulo — SP",
    status: "Agendado",
  },
  {
    id: "tr2",
    title: "Operação segura de bombas hidráulicas",
    brand: "Marzocchi",
    client: "Mineração Serra Azul",
    date: "2026-07-30",
    location: "Belo Horizonte — MG",
    status: "Confirmado",
  },
  {
    id: "tr3",
    title: "Manutenção preventiva de equipamentos Held",
    brand: "Held",
    client: "Refinaria Sul Petróleo",
    date: "2026-07-18",
    location: "Rio de Janeiro — RJ",
    status: "Concluído",
  },
];
